import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

import { TodosView } from "~/modules/todos/views";

const Home: NextPage = () => {
  const { isSignedIn, user } = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="h-[200px] bg-[url('/images/bg-mobile-light.jpg')] bg-cover px-6 pt-12">
        <div className="flex items-center justify-between">
          <h1 className="text-2xl font-bold tracking-widest text-white">
            TODO
          </h1>
          <div>
            <span className="mr-3">🌕</span>
            {isSignedIn ? <SignOutButton /> : <SignInButton />}
            {isSignedIn && <span className="ml-3">{user.firstName}</span>}
          </div>
        </div>
      </header>
      <main className="px-6">
        {isSignedIn ? (
          <TodosView className="-mt-20" />
        ) : (
          <div>Sign in to see your todos</div>
        )}
      </main>
    </>
  );
};

export default Home;
