import { SignInButton, useUser } from "@clerk/nextjs";
import type { NextPage } from "next";
import Head from "next/head";

import { Spinner } from "~/components/Spinner";
import { TodosView } from "~/modules/todos/views";

const Home: NextPage = () => {
  const { isSignedIn, isLoaded } = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {!isLoaded && <Spinner size={40} className="mt-4 flex justify-center" />}
      {isLoaded &&
        (isSignedIn ? (
          <TodosView className="-mt-20 md:-mt-32" />
        ) : (
          <div className="mt-4 text-center">
            <SignInButton>
              <span className="cursor-pointer underline">Sign in</span>
            </SignInButton>{" "}
            to see your todos
          </div>
        ))}
    </>
  );
};

export default Home;
